version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
  minijira-service:
    build:
      context: ./MiniJira-Service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  minijira-frontend:
    build:
      context: ./MiniJira-Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
